export const ANGOLA_PROVINCES = [
  "Bengo",
  "Benguela",
  "Bie",
  "Cabinda",
  "Cubango",
  "Cuando",
  "Cuanza Norte",
  "Cuanza Sul",
  "Cunene",
  "Huambo",
  "Huila",
  "Icolo e Bengo",
  "Luanda",
  "Lunda Norte",
  "Lunda Sul",
  "Malanje",
  "Moxico",
  "Moxico Leste",
  "Namibe",
  "Uige",
  "Zaire",
];

export const ANGOLA_AREA_SUGGESTIONS = {
  Bengo: ["Caxito", "Dande", "Ambriz", "Bula Atumba"],
  Benguela: ["Benguela", "Lobito", "Baia Farta", "Catumbela"],
  Bie: ["Cuito", "Camacupa", "Andulo", "Chinguar"],
  Cabinda: ["Cabinda", "Cacongo", "Belize", "Buco Zau"],
  Cubango: ["Menongue", "Cuito Cuanavale", "Cuchi", "Calai"],
  Cuando: ["Mavinga", "Dirico", "Rivungo", "Cuangar"],
  "Cuanza Norte": ["Ndalatando", "Cambambe", "Lucala", "Golungo Alto"],
  "Cuanza Sul": ["Sumbe", "Porto Amboim", "Gabela", "Waku Kungo"],
  Cunene: ["Ondjiva", "Cahama", "Xangongo", "Namacunde"],
  Huambo: ["Huambo", "Caala", "Bailundo", "Longonjo"],
  Huila: ["Lubango", "Cacula", "Caconda", "Matala"],
  "Icolo e Bengo": ["Catete", "Sequele", "Calumbo", "Bom Jesus"],
  Luanda: ["Luanda", "Belas", "Cacuaco", "Cazenga", "Kilamba Kiaxi", "Talatona", "Viana"],
  "Lunda Norte": ["Dundo", "Cambulo", "Lucapa", "Capenda Camulemba"],
  "Lunda Sul": ["Saurimo", "Cacolo", "Dala", "Muconda"],
  Malanje: ["Malanje", "Cacuso", "Calandula", "Quela"],
  Moxico: ["Luena", "Camanongue", "Leua", "Luau"],
  "Moxico Leste": ["Cazombo", "Alto Zambeze", "Lumbala Nguimbo", "Macondo"],
  Namibe: ["Mocamedes", "Tombwa", "Camucuio", "Bibala"],
  Uige: ["Uige", "Negage", "Maquela do Zombo", "Damba"],
  Zaire: ["Mbanza Congo", "Soyo", "Nzeto", "Tomboco"],
};
